import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const ADMIN_USER = await prisma.user.findFirst({
  where: {
    isAdmin: true,
  },
});

const ADMIN_USER_ID = ADMIN_USER?.id || "";

export const exercisesData = [
  {
    userId: ADMIN_USER_ID,
    name: "Barbell Squat",
    description:
      "A fundamental lower-body exercise that targets the quads, hamstrings, and glutes.",
    muscleGroup: "Legs",
    equipment: ["Barbell", "Squat Rack"],
    image: "barbell-squat.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Deadlift",
    description:
      "A compound lift that strengthens the posterior chain, including hamstrings, glutes, and lower back.",
    muscleGroup: "Back",
    equipment: ["Barbell"],
    image: "deadlift.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Bench Press",
    description:
      "Targets the chest, shoulders, and triceps with heavy pressing movement.",
    muscleGroup: "Chest",
    equipment: ["Barbell", "Bench"],
    image: "bench-press.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Overhead Press",
    description:
      "A shoulder-dominant pressing movement that also engages the triceps and core.",
    muscleGroup: "Shoulders",
    equipment: ["Barbell"],
    image: "overhead-press.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Pull-Up",
    description: "A bodyweight exercise targeting the back and biceps.",
    muscleGroup: "Back",
    equipment: ["Pull-Up Bar"],
    image: "pull-up.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Barbell Row",
    description:
      "Strengthens the upper back, traps, and lats using a bent-over pulling motion.",
    muscleGroup: "Back",
    equipment: ["Barbell"],
    image: "barbell-row.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Romanian Deadlift",
    description:
      "Focuses on hamstring and glute development with a hip hinge movement.",
    muscleGroup: "Hamstrings",
    equipment: ["Barbell"],
    image: "romanian-deadlift.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Lunges",
    description:
      "A single-leg movement that strengthens the quads, glutes, and hamstrings.",
    muscleGroup: "Legs",
    equipment: ["Dumbbells"],
    image: "lunges.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Incline Dumbbell Press",
    description:
      "Targets the upper chest and front delts with a pressing motion.",
    muscleGroup: "Chest",
    equipment: ["Dumbbells", "Incline Bench"],
    image: "incline-dumbbell-press.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Dumbbell Shoulder Press",
    description:
      "A vertical pressing movement for shoulder hypertrophy and strength.",
    muscleGroup: "Shoulders",
    equipment: ["Dumbbells"],
    image: "dumbbell-shoulder-press.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Lat Pulldown",
    description: "Machine-based exercise targeting the lats and upper back.",
    muscleGroup: "Back",
    equipment: ["Lat Pulldown Machine"],
    image: "lat-pulldown.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Seated Cable Row",
    description:
      "Strengthens the middle back and biceps through horizontal pulling.",
    muscleGroup: "Back",
    equipment: ["Cable Machine"],
    image: "seated-cable-row.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Leg Press",
    description:
      "Machine-based compound movement targeting quads, hamstrings, and glutes.",
    muscleGroup: "Legs",
    equipment: ["Leg Press Machine"],
    image: "leg-press.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Bulgarian Split Squat",
    description:
      "Unilateral lower-body exercise that targets quads and glutes.",
    muscleGroup: "Legs",
    equipment: ["Dumbbells", "Bench"],
    image: "bulgarian-split-squat.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Barbell Hip Thrust",
    description: "Focuses on glute development with a hip extension motion.",
    muscleGroup: "Glutes",
    equipment: ["Barbell", "Bench"],
    image: "hip-thrust.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Hammer Curl",
    description: "Targets the biceps and forearms using a neutral grip curl.",
    muscleGroup: "Arms",
    equipment: ["Dumbbells"],
    image: "hammer-curl.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Skull Crushers",
    description:
      "Isolation exercise for the triceps using a lying extension motion.",
    muscleGroup: "Arms",
    equipment: ["EZ Bar", "Bench"],
    image: "skull-crushers.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Chest Fly",
    description: "Isolation movement for the chest performed with dumbbells.",
    muscleGroup: "Chest",
    equipment: ["Dumbbells", "Bench"],
    image: "chest-fly.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Calf Raise",
    description: "Strengthens the calves using a standing or seated motion.",
    muscleGroup: "Calves",
    equipment: ["Machine", "Dumbbells"],
    image: "calf-raise.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
  {
    userId: ADMIN_USER_ID,
    name: "Face Pull",
    description:
      "Improves rear delts and shoulder health using a cable system.",
    muscleGroup: "Shoulders",
    equipment: ["Cable Machine"],
    image: "face-pull.png",
    isPublic: false,
    isDefault: true,
    type: "strength",
  },
];
